version: '3.9'

services:
  db:
    image: postgres:17.3-alpine
    shm_size: 128mb
    hostname: sportevents-db
    environment:
      POSTGRES_USER: sportevents-user
      POSTGRES_PASSWORD: 13bzXtK9a57o6zna7l0t
      POSTGRES_DB: sportevents_db
    ports:
      - '5432:5432'
  redis:
    hostname: sportevents-redis
    image: redis:7.4.2-alpine
    ports:
      - '6379:6379'

  sportevents-storage:
    hostname: sportevents-storage
    image: sportevents-storage
    build:
      dockerfile: ./storage/Dockerfile
    ports:
      - '8080:8080'

  sportevents-retrieval:
    hostname: sportevents-retrieval
    image: sportevents-retrieval
    build:
      dockerfile: ./retrieval/Dockerfile
    ports:
      - '8081:8080'

